### ISSUE TITLE
Puppetfile reference for dev-sec/puppet-apache-hardening

### ISSUE THREAD

**Issue by amitoj** [dev-sec/puppet-apache-hardening#15]
Hi,

I'm building a puppet provisioning based on dev-sec os and ssh hardening.
Also want to include the apache hardening module.

What is the Puppetfile entry for referencing apache hardening module? 
(Similar to mod 'hardening/os_hardening')

Regards,
Amitoj

**Comment by cdenneen** [comment]
@amitoj you can use this:
```
mod 'apache_hardening', :git => "https://github.com/hardening-io/puppet-apache-hardening.git"
```
but this module needs some love for Puppet4

**Comment by tuxmea** [comment]
Question is answered. Please reopen in case that this answer is not working.
